### ISSUE TITLE
Direct login

### ISSUE THREAD

**Issue by EndKingdom-Owner** [EndKingdom/EnderAuth-BETA#1]
Because it easyer to register and login plss

**Comment by matthew4444** [comment]
And u should add custom login and join msg's in config.yml file like lbsg,and theoption to login via sql and  the option to login without typing /login aka by typing paasword in chat, and  when player typespasswodd in chat make it so tyt it would say  dont share your password.

**Comment by flaxues** [comment]
oops

**Comment by matthew4444** [comment]
Hey

**Comment by matthew4444** [comment]
look at matthew4444 plugins please

**Comment by EndKingdom-Owner** [comment]
Why

**Comment by EndKingdom-Owner** [comment]
We need Work on this auth
